(()=>{
 const channel='clearplay-v1';let settings={},status={},indicator,sendKey='';
 const post=(type,data={})=>window.postMessage({channel,direction:'in',type,...data},location.origin);
 const send=async m=>{try{return await chrome.runtime.sendMessage(m);}catch{return {};}};
 function paint(){if(!document.body)return;if(!indicator){indicator=document.createElement('button');indicator.id='clearplay-status';indicator.type='button';Object.assign(indicator.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'2000',border:'1px solid #ffffffa8',borderRadius:'22px',background:'#f3f4f5dd',color:'#30313d',backdropFilter:'blur(18px) saturate(1.5)',padding:'7px 11px',font:'11px system-ui',boxShadow:'0 3px 12px #0004',cursor:'pointer'});indicator.onclick=()=>{post('bypass',{value:!status.bypass});};document.body.append(indicator);}indicator.hidden=!settings.indicator||location.pathname!=='/watch'||!!document.fullscreenElement;indicator.textContent=status.bypass?'Clearplay · bypassed':status.state==='locked'?`Clearplay · ${status.actual}`:'Clearplay · '+({buffering:'buffering',limited:status.target,paused:'off',ad:'ad',error:'check settings',unsupported:'unavailable',switching:'switching',waiting:'waiting for HD','buffer-timeout':'press Play'}[status.state]||'checking');indicator.title=(status.message||'Connecting to player')+' · Click to toggle bypass for this video';}
 window.addEventListener('message',e=>{const m=e.data;if(e.source!==window||e.origin!==location.origin||m?.channel!==channel||m.direction!=='out'||m.type!=='status')return;status={state:String(m.state||'').slice(0,30),message:String(m.message||'').slice(0,200),target:String(m.target||'').slice(0,20),actual:String(m.actual||'').slice(0,20),decoded:String(m.decoded||'').slice(0,30),bufferSeconds:Number(m.bufferSeconds)||0,bypass:m.bypass===true,enabled:m.enabled===true};paint();const key=JSON.stringify(status);if(key!==sendKey){sendKey=key;send({type:'status',status});}});
 chrome.runtime.onMessage.addListener((m,_,reply)=>{if(m.type==='status'){reply(status);post('status');}if(m.type==='bypass'){post('bypass',{value:m.value});reply({ok:true});}});
 chrome.storage.onChanged.addListener((c,area)=>{if(area==='local'&&c.settings){settings=c.settings.newValue||{};post('settings',{settings});paint();}});
 (async()=>{const r=await send({type:'init'});settings=r.settings||{};post('settings',{settings});paint();})();
})();
