const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),Q=require(path.join(root,'quality.js'));
const flush=()=>new Promise(r=>setImmediate(r));
function env(){const dom=new JSDOM('<div id="movie_player"><video></video></div>',{url:'https://www.youtube.com/watch?v=one',runScripts:'outside-only'}),w=dom.window,v=w.document.querySelector('video');let height=720,paused=false,buffer=30,clock=Date.now();const calls=[],messages=[];Object.defineProperties(v,{videoHeight:{get:()=>height},videoWidth:{get:()=>height*16/9},duration:{get:()=>180},currentTime:{get:()=>10},readyState:{get:()=>4},paused:{get:()=>paused},buffered:{get:()=>({length:1,start:()=>0,end:()=>10+buffer})}});v.pause=()=>paused=true;v.play=()=>{paused=false;return Promise.resolve()};w.setInterval=f=>w.tick=f;w.Date.now=()=>clock;w.postMessage=m=>messages.push(m);w.eval(fs.readFileSync(path.join(root,'quality.js'),'utf8'));w.ClearplayMenu={select:async(p,t,valid)=>{calls.push(t);return {ok:valid(),height:t==='auto'?0:t==='highest'?2160:Number(t)};}};w.eval(fs.readFileSync(path.join(root,'player.js'),'utf8'));const post=m=>w.dispatchEvent(new w.MessageEvent('message',{source:w,origin:w.location.origin,data:{channel:'clearplay-v1',direction:'in',...m}}));return {dom,w,v,post,calls,messages,height:n=>height=n,time:n=>clock+=n,paused:()=>paused,buffer:n=>buffer=n};}
test('Preference selection and validation remain correct',()=>{assert.equal(Q.choose(['hd720','hd1440'],'1080'),'hd1440');assert.equal(Q.choose(['hd720'],'1080'),'hd720');assert.equal(Q.clean({target:'garbage'}).target,'1080')});
test('One native quality selection, decoded resolution required before locked',async t=>{const e=env();t.after(()=>e.dom.window.close());e.post({type:'settings',settings:Q.defaults()});await flush();for(let i=0;i<100;i++){e.time(3000);e.w.tick();}assert.deepEqual(e.calls,['1080']);assert.equal(e.messages.at(-1).state,'waiting');e.height(1080);e.w.tick();assert.equal(e.messages.at(-1).state,'locked');});
test('Bypass uses Auto once; restore uses quality once without restarting buffering',async t=>{const e=env();t.after(()=>e.dom.window.close());e.post({type:'settings',settings:{...Q.defaults(),bufferSeconds:20}});await flush();e.post({type:'bypass',value:true});await flush();e.post({type:'bypass',value:true});for(let i=0;i<20;i++)e.w.tick();assert.deepEqual(e.calls,['1080','auto']);e.post({type:'bypass',value:false});await flush();e.height(1080);e.w.tick();assert(!e.paused());assert.deepEqual(e.calls,['1080','auto','1080']);});
test('Cosmetic settings, fullscreen and status polls do not issue quality commands',async t=>{const e=env();t.after(()=>e.dom.window.close());e.post({type:'settings',settings:Q.defaults()});await flush();e.post({type:'settings',settings:{...Q.defaults(),sound:false,indicator:false}});e.w.document.dispatchEvent(new e.w.Event('fullscreenchange'));for(let i=0;i<30;i++)e.post({type:'status'});assert.deepEqual(e.calls,['1080']);});
test('Disabled initial load leaves player alone; disabling an active lock releases once',async t=>{const e=env();t.after(()=>e.dom.window.close());e.post({type:'settings',settings:{...Q.defaults(),enabled:false}});await flush();assert.equal(e.calls.length,0);e.post({type:'settings',settings:Q.defaults()});await flush();e.post({type:'settings',settings:{...Q.defaults(),enabled:false}});await flush();assert.deepEqual(e.calls,['1080','auto']);});
test('New video clears bypass; failed menu attempts are bounded',async t=>{const e=env();t.after(()=>e.dom.window.close());e.post({type:'settings',settings:Q.defaults()});await flush();e.post({type:'bypass',value:true});await flush();e.w.history.pushState({},'','/watch?v=two');e.w.tick();await flush();assert.equal(e.calls.at(-1),'1080');e.w.ClearplayMenu.select=async()=>{e.calls.push('failed');return {ok:false,reason:'missing'}};e.post({type:'settings',settings:{...Q.defaults(),target:'2160'}});await flush();for(let i=0;i<10;i++){e.time(5000);e.w.tick();await flush();}assert.equal(e.calls.filter(x=>x==='failed').length,3);});
test('Menu selects an available non-premium tier and closes its own menu',async t=>{const d=new JSDOM('<div id="movie_player"><button class="ytp-settings-button" aria-expanded="false"></button><div class="ytp-menuitem"><span class="ytp-menuitem-label">Quality</span><span>720p</span></div><div role="menuitemradio">2160p Premium</div><div role="menuitemradio">1440p HD</div><div role="menuitemradio">720p</div><div role="menuitemradio">Auto</div></div>',{runScripts:'outside-only'});t.after(()=>d.window.close());const w=d.window,p=w.document.querySelector('#movie_player'),b=p.querySelector('button');for(const el of p.querySelectorAll('*'))el.getClientRects=()=>[{}];let selected='';b.onclick=()=>b.setAttribute('aria-expanded',String(b.getAttribute('aria-expanded')!=='true'));for(const el of p.querySelectorAll('[role]'))el.onclick=()=>selected=el.textContent;w.eval(fs.readFileSync(path.join(root,'menu.js'),'utf8'));const r=await w.ClearplayMenu.select(p,'1080');assert(r.ok);assert.equal(selected,'1440p HD');assert.equal(b.getAttribute('aria-expanded'),'false');b.setAttribute('aria-expanded','true');assert.equal((await w.ClearplayMenu.select(p,'auto')).reason,'busy');});
test('Prebuffer waits for selected decoded resolution, resumes once, and never starts user-paused video',async t=>{const e=env();t.after(()=>e.dom.window.close());e.buffer(0);e.post({type:'settings',settings:{...Q.defaults(),bufferSeconds:5}});await flush();e.w.tick();assert(!e.paused());e.height(1080);e.w.tick();assert(e.paused());e.buffer(8);e.w.tick();assert(!e.paused());e.buffer(0);e.w.tick();assert(!e.paused());});
test('Ad playback is untouched; navigation cancels an in-flight selection',async t=>{const e=env();t.after(()=>e.dom.window.close());e.w.document.querySelector('#movie_player').classList.add('ad-showing');e.post({type:'settings',settings:Q.defaults()});await flush();assert.equal(e.calls.length,0);e.w.document.querySelector('#movie_player').classList.remove('ad-showing');let check;e.w.ClearplayMenu.select=(p,target,valid)=>{check=valid;return new Promise(()=>{});};e.w.tick();assert(check());e.w.document.dispatchEvent(new e.w.Event('yt-navigate-start'));assert(!check());});
